#! /bin/bash

HOME=${HOME}
ME=$(whoami)
GID=$(getent passwd $(whoami) | awk -F: '{print $4 }')
podman run  -it -v $(pwd):/work  -v ${HOME}:${HOME} --userns=keep-id:uid=${UID},gid=${GID} --hostuser=${ME} --rm  dev-env $@
