#! /bin/bash

KEED_USERID=""
if [[ $(id -ru) != "0" ]]; then
    KEED_USERID="--userns=keep-id"
fi

podman run  -it --security-opt label=disable -v $(pwd):/work  -v ${HOME}:${HOME} ${KEED_USERID} --rm  dev-env "$@"
