#!/bin/sh
delete_file() {
FILE=$1
if [ -e "/host/bin/${FILE}" ]; then
	/usr/bin/rm -vf /host/bin/${FILE}
elif [ -e "/host/usr/local/bin/${FILE}" ]; then
        /usr/bin/rm -vf /host/usr/local/bin/${FILE}
else
	echo "${FILE} not present, nothing to remove"
fi
}

delete_file dev-env
